<?php
/**
 * @file
 * @reviewed by Ha
 * @date Feb 04, 2016
 */

// Plugin definition.
$plugin = array(
  'title' => t('Two column 70/30'),
  'category' => t('Kopatheme'),
  'icon' => 'twocol_70_30.png',
  'theme' => 'twocol_70_30',
  'css' => 'twocol_70_30.css',
  'regions' => array(
    'top' => t('Top'),
    'center' => t('Center'),
    'right' => t('Right'),
    'bottom' => t('Bottom'),
  ),
);
